/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Female2.glb -o src/components/Female.tsx -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

// Define the custom prop type
type FemaleProps = JSX.IntrinsicElements["group"] & {
  toggleDebug?: boolean;
  togglePivot?: boolean;
  uploadedImages?: any
};

type GLTFResult = GLTF & {
  nodes: {
    Mannequin_Fm: THREE.Mesh
  }
  materials: {
    ['uv.002']: THREE.MeshStandardMaterial
  }
}

export function Female({ toggleDebug = false, togglePivot = false, uploadedImages, ...props }: FemaleProps) {
  const { nodes, materials } = useGLTF('/models/Female.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mannequin_Fm.geometry} material={materials['uv.002']} />
    </group>
  )
}

useGLTF.preload('/models/Female.glb')
