/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Male2.glb -o src/components/Male.tsx -r public 
*/

import * as THREE from "three";
import React, { useState, useEffect } from "react";
import { PivotControls, useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Tattoo } from "./Tattoo";
import { maleBodyPartConfigs, bodyParts } from "@/helper/bodyPart";
import { stringCoverter } from "@/helper/stringCoverter";

// Define the custom prop type
type MaleProps = JSX.IntrinsicElements["group"] & {
  toggleDebug?: boolean;
  togglePivot?: boolean;
  uploadedImages?: any;
  setTattooScaleWithPart: (
    part: string,
    scale: [number, number, number]
  ) => void;
};

// Use stringCoverter to generate the parts array
const parts = bodyParts.map(stringCoverter);

type GLTFResult = GLTF & {
  nodes: {
    Mannequin_ML: THREE.Mesh;
  };
  materials: {
    ["uv.003"]: THREE.MeshStandardMaterial;
  };
};

export function Male({
  toggleDebug = false,
  togglePivot = false,
  uploadedImages,
  setTattooScaleWithPart,
  ...props
}: MaleProps) {
  const { nodes, materials } = useGLTF("/models/Male.glb") as GLTFResult;
  const defaultMaterial = "./tattoo_hub.png";

  // Initialize state for all parts
  const [state, setState] = useState(() =>
    parts.reduce((acc, part) => {
      const initialScale = maleBodyPartConfigs[part].scale as [
        number,
        number,
        number
      ];
      // Pass initial scale to parent only if there is an uploaded image for the part
      if (uploadedImages?.[part]) {
        setTattooScaleWithPart(part, initialScale);
      }
      acc[part] = {
        position: [...maleBodyPartConfigs[part].position],
        scale: [...maleBodyPartConfigs[part].scale],
        rotation: [...maleBodyPartConfigs[part].rotation],
      };
      return acc;
    }, {} as Record<string, { position: [number, number, number]; scale: [number, number, number]; rotation: [number, number, number] }>)
  );

  const textures = useTexture(
    parts.reduce((acc, part) => {
      acc[part] = uploadedImages[part] || defaultMaterial;
      return acc;
    }, {} as Record<string, string>)
  );

  return (
    <group {...props} dispose={null} scale={[1.5, 1.5, 1.5]}>
      <mesh
        geometry={nodes.Mannequin_ML.geometry}
        material={materials["uv.003"]}
        material-aoMapIntensity={1}
      >
        {parts.map(
          (part) =>
            uploadedImages[part] &&
            textures[part] && (
              <React.Fragment key={part}>
                <PivotControls
                  scale={0.3}
                  activeAxes={[true, true, true]}
                  offset={
                    maleBodyPartConfigs[part]["position"][0] > 0
                      ? [
                          maleBodyPartConfigs[part]["position"][0] + 0.5,
                          maleBodyPartConfigs[part]["position"][1],
                          maleBodyPartConfigs[part]["position"][2],
                        ]
                      : [
                          maleBodyPartConfigs[part]["position"][0] - 0.5,
                          maleBodyPartConfigs[part]["position"][1],
                          maleBodyPartConfigs[part]["position"][2],
                        ]
                  }
                  visible={togglePivot}
                  onDrag={(local) => {
                    const position = new THREE.Vector3();
                    const scale = new THREE.Vector3();
                    const quaternion = new THREE.Quaternion();
                    local.decompose(position, quaternion, scale);
                    const rotation = new THREE.Euler().setFromQuaternion(
                      quaternion
                    );
                    setState((prev) => ({
                      ...prev,
                      [part]: {
                        position: [
                          position.x + maleBodyPartConfigs[part].position[0],
                          position.y + maleBodyPartConfigs[part].position[1],
                          position.z + maleBodyPartConfigs[part].position[2],
                        ],
                        scale: [
                          maleBodyPartConfigs[part].scale[0] * scale.x,
                          maleBodyPartConfigs[part].scale[1] * scale.y,
                          maleBodyPartConfigs[part].scale[2] * scale.z,
                        ],
                        rotation: [
                          rotation.x + maleBodyPartConfigs[part].rotation[0],
                          rotation.y + maleBodyPartConfigs[part].rotation[1],
                          rotation.z + maleBodyPartConfigs[part].rotation[2],
                        ],
                      },
                    }));

                    const newScale: [number, number, number] = [
                      maleBodyPartConfigs[part].scale[0] * scale.x,
                      maleBodyPartConfigs[part].scale[1] * scale.y,
                      maleBodyPartConfigs[part].scale[2] * scale.z,
                    ];
                    setTattooScaleWithPart(part, newScale);
                  }}
                />
                <Tattoo
                  position={state[part].position}
                  scale={state[part].scale}
                  rotation={state[part].rotation}
                  debugMode={toggleDebug}
                  tattoo={textures[part]}
                />
              </React.Fragment>
            )
        )}
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Male.glb");
